// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyAkb__l8R44KV122NEVmRnS0SJm9vpgQ',
    appId: '1:787413281430:web:fd9e466e4d9cdfc286b0b7',
    messagingSenderId: '787413281430',
    projectId: 'modelexam-2ca47',
    authDomain: 'modelexam-2ca47.firebaseapp.com',
    storageBucket: 'modelexam-2ca47.appspot.com',
    measurementId: 'G-X89GLMGL67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkH46bPReM-3IB--ZjG7Ig1VkmwynPf-U',
    appId: '1:787413281430:android:ff65d0f3e8abf55086b0b7',
    messagingSenderId: '787413281430',
    projectId: 'modelexam-2ca47',
    storageBucket: 'modelexam-2ca47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiUbF1RT7_-I8sypC7RiMdK0WU51meC08',
    appId: '1:787413281430:ios:a20f63c116c0683986b0b7',
    messagingSenderId: '787413281430',
    projectId: 'modelexam-2ca47',
    storageBucket: 'modelexam-2ca47.appspot.com',
    iosBundleId: 'com.example.modelexam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyAkb__l8R44KV122NEVmRnS0SJm9vpgQ',
    appId: '1:787413281430:web:ca904c3c8de30d4486b0b7',
    messagingSenderId: '787413281430',
    projectId: 'modelexam-2ca47',
    authDomain: 'modelexam-2ca47.firebaseapp.com',
    storageBucket: 'modelexam-2ca47.appspot.com',
    measurementId: 'G-BS8YXFL3RB',
  );
}
